# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "github_dark_colorblind"

# Prompt layout configuration
format = """$directory$git_branch$git_status$package$rust$golang$fill$time
$character"""

[time]
disabled = false
format = '[$time]($style)'
style = "bold blue"
time_format = "%Y-%m-%d %H:%M:%S"
use_12hr = false
utc_time_offset = "local"


# Starship modules
[character]
# Note the use of Catppuccin color 'peach'
success_symbol = "[(green) ❯](peach)"
error_symbol = "[(red) ❯](peach)"
vimcmd_symbol = "[❮](subtext1)"       # For use with zsh-vi-mode

[git_branch]
style = "bold mauve"

[directory]
truncation_length = 4
style = "bold lavender"

# Palette definitions
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.macos_classic_light]
rosewater = "#C5060B"
flamingo = "#C5060B"
pink = "#a440b5"
mauve = "#6f42c1"
red = "#C5060B"
maroon = "#C5060B"
peach = "#9e7008"
yellow = "#C99401"
green = "#036A07"
teal = "#007fff"
sky = "#007fff"
sapphire = "#0433ff"
blue = "#0433ff"
lavender = "#1f6ae2"
text = "#000000"
subtext1 = "#505050"
subtext0 = "#929292"
overlay2 = "#929292"
overlay1 = "#D9D9D9"
overlay0 = "#E9E9E9"
surface2 = "#E9E9E9"
surface1 = "#F9F9F9"
surface0 = "#F9F9F9"
base = "#ffffff"
mantle = "#F9F9F9"
crust = "#E9E9E9"

[palettes.macos_classic_dark]
rosewater = "#DD6F61"
flamingo = "#DD6F61"
pink = "#D86DE9"
mauve = "#AE30C2"
red = "#A8473B"
maroon = "#DD6F61"
peach = "#E1D797"
yellow = "#857F5C"
green = "#76BA53"
teal = "#3DB6B0"
sky = "#5BDFD8"
sapphire = "#3f72e2"
blue = "#81A9F6"
lavender = "#81A9F6"
text = "#CACCCA"
subtext1 = "#9E9E9E"
subtext0 = "#7A7A7A"
overlay2 = "#5C5C5C"
overlay1 = "#3E3E3E"
overlay0 = "#2A2A2A"
surface2 = "#202020"
surface1 = "#1A1A1A"
surface0 = "#161616"
base = "#131313"
mantle = "#0F0F0F"
crust = "#0A0A0A"

[palettes.macos_classic_dark_xcode]
rosewater = "#E66969"
flamingo = "#E66969"
pink = "#D86DE9"
mauve = "#AE30C2"
red = "#D73737"
maroon = "#E66969"
peach = "#AE9513"
yellow = "#705F00"
green = "#76BA53"
teal = "#37D0D7"
sky = "#69DDE6"
sapphire = "#3f72e2"
blue = "#81A9F6"
lavender = "#81A9F6"
text = "#E8E4CF"
subtext1 = "#9E9E9E"
subtext0 = "#7A7A7A"
overlay2 = "#5C5C5C"
overlay1 = "#3E3E3E"
overlay0 = "#2A2A2A"
surface2 = "#202020"
surface1 = "#1A1A1A"
surface0 = "#161616"
base = "#131313"
mantle = "#0F0F0F"
crust = "#0A0A0A"

[palettes.github_dark]
rosewater = "#ff7b72"
flamingo = "#ffa198"
pink = "#f778ba"
mauve = "#bc8cff"
red = "#ff7b72"
maroon = "#da3633"
peach = "#ffa657"
yellow = "#d29922"
green = "#3fb950"
teal = "#39c5cf"
sky = "#79c0ff"
sapphire = "#58a6ff"
blue = "#58a6ff"
lavender = "#d2a8ff"
text = "#e6edf3"
subtext1 = "#b1bac4"
subtext0 = "#8b949e"
overlay2 = "#6e7681"
overlay1 = "#484f58"
overlay0 = "#30363d"
surface2 = "#21262d"
surface1 = "#161b22"
surface0 = "#0d1117"
base = "#0d1117"
mantle = "#161b22"
crust = "#30363d"

[palettes.github_light]
rosewater = "#cf222e"
flamingo = "#a40e26"
pink = "#bf3989"
mauve = "#8250df"
red = "#cf222e"
maroon = "#a40e26"
peach = "#fb8500"
yellow = "#9a6700"
green = "#1a7f37"
teal = "#1b7c83"
sky = "#0969da"
sapphire = "#0969da"
blue = "#0969da"
lavender = "#6639ba"
text = "#24292f"
subtext1 = "#57606a"
subtext0 = "#6e7781"
overlay2 = "#8c959f"
overlay1 = "#afb8c1"
overlay0 = "#d0d7de"
surface2 = "#d8dee4"
surface1 = "#f3f4f6"
surface0 = "#f6f8fa"
base = "#ffffff"
mantle = "#f6f8fa"
crust = "#d0d7de"

[palettes.github_dark_dimmed]
rosewater = "#f47067"
flamingo = "#ff938a"
pink = "#e275ad"
mauve = "#b083f0"
red = "#f47067"
maroon = "#cc4b49"
peach = "#f69d50"
yellow = "#c69026"
green = "#57ab5a"
teal = "#39c5cf"
sky = "#6cb6ff"
sapphire = "#539bf5"
blue = "#539bf5"
lavender = "#dcbdfb"
text = "#adbac7"
subtext1 = "#909dab"
subtext0 = "#768390"
overlay2 = "#636e7b"
overlay1 = "#545d68"
overlay0 = "#444c56"
surface2 = "#373e47"
surface1 = "#2d333b"
surface0 = "#22272e"
base = "#22272e"
mantle = "#2d333b"
crust = "#444c56"

[palettes.github_dark_high_contrast]
rosewater = "#ff6a69"
flamingo = "#ff9492"
pink = "#ff9bce"
mauve = "#b780ff"
red = "#ff6a69"
maroon = "#e82a2f"
peach = "#fe9a2d"
yellow = "#e09b13"
green = "#09b43a"
teal = "#76e3ea"
sky = "#71b7ff"
sapphire = "#409eff"
blue = "#409eff"
lavender = "#cb9eff"
text = "#f0f3f6"
subtext1 = "#bdc4cc"
subtext0 = "#9ea7b3"
overlay2 = "#7a828e"
overlay1 = "#525964"
overlay0 = "#272b33"
surface2 = "#272b33"
surface1 = "#272b33"
surface0 = "#0a0c10"
base = "#0a0c10"
mantle = "#272b33"
crust = "#525964"

[palettes.github_light_high_contrast]
rosewater = "#a0111f"
flamingo = "#86061d"
pink = "#9c185d"
mauve = "#622cbc"
red = "#a0111f"
maroon = "#86061d"
peach = "#873800"
yellow = "#744500"
green = "#024c1a"
teal = "#055d20"
sky = "#023b95"
sapphire = "#023b95"
blue = "#023b95"
lavender = "#622cbc"
text = "#0e1116"
subtext1 = "#20252c"
subtext0 = "#4b535d"
overlay2 = "#66707b"
overlay1 = "#88929d"
overlay0 = "#acb6c0"
surface2 = "#ced5dc"
surface1 = "#e7ecf0"
surface0 = "#e7ecf0"
base = "#ffffff"
mantle = "#e7ecf0"
crust = "#20252c"

[palettes.github_dark_colorblind]
rosewater = "#ec8e2c"
flamingo = "#fdac54"
pink = "#f778ba"
mauve = "#bc8cff"
red = "#ec8e2c"
maroon = "#b76100"
peach = "#ffa657"
yellow = "#d29922"
green = "#58a6ff"
teal = "#76e3ea"
sky = "#79c0ff"
sapphire = "#58a6ff"
blue = "#58a6ff"
lavender = "#d2a8ff"
text = "#c9d1d9"
subtext1 = "#b1bac4"
subtext0 = "#8b949e"
overlay2 = "#6e7681"
overlay1 = "#484f58"
overlay0 = "#30363d"
surface2 = "#21262d"
surface1 = "#161b22"
surface0 = "#0d1117"
base = "#0d1117"
mantle = "#161b22"
crust = "#30363d"

[palettes.github_light_colorblind]
rosewater = "#cf222e"
flamingo = "#a40e26"
pink = "#bf3989"
mauve = "#8250df"
red = "#cf222e"
maroon = "#a40e26"
peach = "#fb8500"
yellow = "#9a6700"
green = "#1a7f37"
teal = "#1b7c83"
sky = "#0969da"
sapphire = "#0969da"
blue = "#0969da"
lavender = "#6639ba"
text = "#24292f"
subtext1 = "#57606a"
subtext0 = "#6e7781"
overlay2 = "#8c959f"
overlay1 = "#afb8c1"
overlay0 = "#d0d7de"
surface2 = "#d8dee4"
surface1 = "#f3f4f6"
surface0 = "#f6f8fa"
base = "#ffffff"
mantle = "#f6f8fa"
crust = "#d0d7de"


[aws]
disabled = true

[buf]
format = '(with [$symbol$version ]($style))'

[bun]
format = '(via [$symbol($version )]($style))'

[c]
format = '(via [$symbol($version(-$name) )]($style))'

[cmake]
format = '(via [$symbol($version )]($style))'

[cobol]
format = '(via [$symbol($version )]($style))'

[crystal]
format = '(via [$symbol($version )]($style))'

[daml]
format = '(via [$symbol($version )]($style))'

[dart]
format = '(via [$symbol($version )]($style))'

[deno]
format = '(via [$symbol($version )]($style))'

[dotnet]
format = '(via [$symbol($version )(🎯 $tfm )]($style))'

[elixir]
format = '(via [$symbol($version \(OTP $otp_version\) )]($style))'

[elm]
format = '(via [$symbol($version )]($style))'

[erlang]
format = '(via [$symbol($version )]($style))'

[fennel]
format = '(via [$symbol($version )]($style))'

[gleam]
format = '(via [$symbol($version )]($style))'

[golang]
format = '(via [$symbol($version )]($style))'

[haskell]
format = '(via [$symbol($version )]($style))'

[helm]
format = '(via [$symbol($version )]($style))'

[java]
format = '(via [$symbol($version )]($style))'

[julia]
format = '(via [$symbol($version )]($style))'

[kotlin]
format = '(via [$symbol($version )]($style))'

[lua]
format = '(via [$symbol($version )]($style))'

[nim]
format = '(via [$symbol($version )]($style))'

[nodejs]
format = '(via [$symbol($version )]($style))'

[ocaml]
format = '(via [$symbol($version )(\($switch_indicator$switch_name\) )]($style))'

[opa]
format = '(via [$symbol($version )]($style))'
[package]
format = '(is [$symbol$version]($style) )'

[perl]
format = '(via [$symbol($version )]($style))'

[php]
format = '(via [$symbol($version )]($style))'

[purescript]
format = '(via [$symbol($version )]($style))'

[python]
format = '(via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style))'

[quarto]
format = '(via [$symbol($version )]($style))'

[raku]
format = '(via [$symbol($version-$vm_version )]($style))'

[red]
format = '(via [$symbol($version )]($style))'

[rlang]
format = '(via [$symbol($version )]($style))'

[ruby]
format = '(via [$symbol($version )]($style))'

[rust]
format = '(via [$symbol($version )]($style))'

[scala]
format = '(via [$symbol($version )]($style))'

[swift]
format = '(via [$symbol($version )]($style))'

[typst]
format = '(via [$symbol($version )]($style))'

[vagrant]
format = '(via [$symbol($version )]($style))'

[vlang]
format = '(via [$symbol($version )]($style))'

[zig]
format = '(via [$symbol($version )]($style))'
